Correct directory for teamsgroups.py
ModuleNotFoundError: No module named 'teamsgroups'

Since pip installed wc18.py and teamsgroups.py in the same directory, took advantage of it and got the directory from the wc18.py file.